version: "3"
services:
  appdb:
    image: postgres
    container_name: "appdb"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/database:/var/lib/postgresql/data
#      - ./initdb:/docker-entrypoint-initdb.d